# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente', models.CharField(max_length=100)),
                ('Edad', models.CharField(max_length=100)),
                ('Motivo_de_Consulta', models.CharField(max_length=100)),
                ('Recomendaciones', models.CharField(max_length=100)),
                ('Receta_Medica', models.CharField(max_length=100)),
            ],
        ),
    ]
